name: hive_dart
description: A collection of useful utility functions for Dart.
version: 0.0.4
license: MIT
repository: https://github.com/yorkjs/hive-dart

environment:
  sdk: ^3.8.2

dependencies:
  intl: ^0.20.2
  decimal: ^3.2.4
  json_annotation: ^4.9.0

dev_dependencies:
  json_serializable: ^6.8.0
  lints: ^6.0.0
  test: ^1.24.0
